#!/bin/sh

if [ "$PKG_UPGRADE" != "1" ]; then
    uci get luci.themes.FoxHound >/dev/null 2>&1 || {
        uci batch <<-EOF
            set luci.themes.FoxHound=/luci-static/foxhound
            set luci.main.mediaurlbase=/luci-static/foxhound
            commit luci
EOF
    }
fi

exit 0